### ISSUE TITLE
Enhance integration tests

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-ogcapi-features10#156]

**Comment by dstenger** [comment]
Integration tests were created and can be run with `mvn clean verify -Pintegration-tests`.

Commit: https://github.com/opengeospatial/ets-ogcapi-features10/commit/243a647f8ebb7b5b05b7e7cec30c87a347545b94

**Comment by lgoltz** [comment]
Soap UI tests are currently failing. Some erros are logged:
```
10:08:25,267 ERROR [SoapUI] An error occurred [com.eviware.soapui.plugins.auto.factories.AutoDiscoveryMethodFactory], see error log for details
java.lang.ClassNotFoundException: com.eviware.soapui.plugins.auto.factories.AutoDiscoveryMethodFactory
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.eviware.soapui.plugins.LoaderBase.loadAutoFactories(LoaderBase.java:113)
	at com.eviware.soapui.plugins.LoaderBase.loadFactories(LoaderBase.java:80)
	at com.eviware.soapui.plugins.PluginLoader.loadPluginFactories(PluginLoader.java:141)
	at com.eviware.soapui.plugins.PluginLoader.loadPlugin(PluginLoader.java:104)
	at com.eviware.soapui.plugins.PluginLoader.loadPlugin(PluginLoader.java:54)
	at com.eviware.soapui.plugins.PluginManager.doInstallPlugin(PluginManager.java:141)
	at com.eviware.soapui.plugins.PluginManager.access$600(PluginManager.java:43)
	at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.computeSequentially(PluginManager.java:420)
	at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.compute(PluginManager.java:377)
	at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.compute(PluginManager.java:365)
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by dstenger** [comment]
The properties were updated: https://github.com/opengeospatial/ets-ogcapi-features10/commit/778b083d396d0af1edb82d911120608922bf08dd

As previously mentioned StackTrace does not affect the test run, I propose to ignore it for now.

**Comment by dstenger** [comment]
Fixed unit test (https://github.com/opengeospatial/ets-ogcapi-features10/commit/d9ca82f37dff50c2f564be88cdd5f7006f4fe402) and integration tests (https://github.com/opengeospatial/ets-ogcapi-features10/commit/470231032e136885c4c54f0e06c2f150588e08d3).

**Comment by dstenger** [comment]
Build with `mvn clean install site -Pintegration-tests,docker` is successful.
