### ISSUE TITLE
Update Maven dependencies

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-ogcapi-features10#157]
Some Maven dependencies are outdated and shall be updated to the current version.

**Comment by dstenger** [comment]
Execution of `mvn org.apache.maven.plugins:maven-dependency-plugin:analyze`:
```
[INFO] --- maven-dependency-plugin:3.0.0:analyze (default-cli) @ ets-ogcapi-features10 ---
[WARNING] Used undeclared dependencies found:
[WARNING]    org.apache.commons:commons-lang3:jar:3.4:compile
[WARNING] Unused declared dependencies found:
[WARNING]    net.jadler:jadler-jetty:jar:1.3.0:test
[WARNING]    com.google.inject:guice:jar:4.0:test
```

Unused declared dependencies are actually needed for build.
Used undeclared dependency was added: https://github.com/opengeospatial/ets-ogcapi-features10/commit/b4d0f6664d21220858202f886edee2c8ab04897f

**Comment by dstenger** [comment]
Updated dependencies jersey-core, rest-assured and jcommander and removed json-path: https://github.com/opengeospatial/ets-ogcapi-features10/commit/24fed17d58ad2391d8c9781b98866acb3397639d

rest-assured might even be updated to v4.

**Comment by lgoltz** [comment]
The update of jcommander causes a failure if the tests are executed with IntelliJ:
```
Exception in thread "main" com.beust.jcommander.ParameterException: Cannot use final field org.opengis.cite.ogcapifeatures10.CommandLineArguments#xmlProps as a parameter; compile-time constant inlining may hide new values written to it.
	at com.beust.jcommander.Parameterized.setFieldAccessible(Parameterized.java:251)
	at com.beust.jcommander.Parameterized.<init>(Parameterized.java:33)
	at com.beust.jcommander.Parameterized.parseArg(Parameterized.java:110)
	at com.beust.jcommander.JCommander.addDescription(JCommander.java:601)
	at com.beust.jcommander.JCommander.createDescriptions(JCommander.java:594)
	at com.beust.jcommander.JCommander.<init>(JCommander.java:249)
	at com.beust.jcommander.JCommander.<init>(JCommander.java:235)
	at com.beust.jcommander.JCommander.<init>(JCommander.java:227)
	at org.opengis.cite.ogcapifeatures10.TestNGController.main(TestNGController.java:64)
```

Fixed with https://github.com/opengeospatial/ets-ogcapi-features10/commit/679284841e9d914328b9279127c7a1aaa28ca455
